#!/bin/sh
# update
# Created: Wed Dec 18 09:14:51 MYT 2013
prefix=/usr/local
plat=$(uname -s)
case "$plat" in
	Darwin) prefix=/opt/local;;
esac

if [ -z "$1" ]; then
	make --no-print-directory -C ~/src/install prefix=$prefix
else
	for i in $*; do
		make --no-print-directory -C ~/src/install prefix=$prefix update$i
	done
fi
make -C ~/src/git-number
make -C ~/src/install ages
echo "DONE $(date)"
