#!/bin/sh
# update
# Created: Wed Dec 18 09:14:51 MYT 2013
if [ -z "$1" ]; then
	exec make --no-print-directory -C ~/src/install
fi

for i in $*; do
	make --no-print-directory -C ~/src/install update$i
done
echo "DONE $(date)"
